name: CI

on: 
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Install dependencies
      run: pip install requests
    
    - name: Make scripts executable
      run: |
        chmod +x get-reposense.py
        chmod +x run.sh
    
    - name: Create report directory
      run: mkdir -p reposense-report
    
    - name: Download RepoSense
      run: ./get-reposense.py --release --overwrite
    
    - name: Show Java version
      run: java -version
    
    - name: Generate report
      run: |
        set -x  # Enable debug output
        java --add-opens java.base/java.time=ALL-UNNAMED -jar RepoSense.jar \
          --config ./configs \
          --since 01/01/2020 \
          --until 31/12/2024 \
          --formats "java md txt" \
          --timezone UTC+08 \
          --output ./reposense-report
    
    - name: Copy frontend files
      run: |
        cp -r frontend/* reposense-report/ || echo "No frontend files to copy"
        touch reposense-report/.nojekyll
    
    - name: List generated files
      run: |
        pwd
        ls -la
        echo "=== RepoSense Report Directory ==="
        ls -la reposense-report/ || echo "Report directory is empty or not created"
        echo "=== RepoSense Report Contents ==="
        find reposense-report -type f
    
    - name: Deploy GitHub pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reposense-report
        force_orphan: true
        enable_jekyll: false
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'docs: update RepoSense report'
