name: CI

on: 
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Install dependencies
      run: pip install requests
    
    - name: Make scripts executable
      run: |
        chmod +x get-reposense.py
        chmod +x run.sh
    
    - name: Generate report
      run: bash ./run.sh
    
    - name: Prepare deployment
      run: |
        # Create deployment directory
        mkdir -p deploy
        
        # Copy required files
        cp -r reposense-report/* deploy/
        cp -r fonts js deploy/
        cp .nojekyll favicon.ico index.html summary.json title.md deploy/
        
        # Create logs directory
        mkdir -p deploy/reposense-logs
        cp reposense-report/reposense.log deploy/reposense-logs/response.log.0 || true
        
        # Create archive
        cd reposense-report
        zip -r ../deploy/archive.zip .
        cd ..
    
    - name: List deployment files
      run: |
        echo "=== Deployment Directory Structure ==="
        ls -la deploy/
        find deploy -type f
    
    - name: Deploy GitHub pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./deploy
        force_orphan: true
        enable_jekyll: false
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'docs: update RepoSense report'
